### ISSUE TITLE
What is SV_ShouldBypassEntity?

### ISSUE THREAD

**Issue by hzqst** [gabuch2/SvenCoopSemiclip#3]
Could not even found the signature or named function in either hw.so or hw.dll
![image](https://user-images.githubusercontent.com/12287588/212227359-1bd89649-7a0f-4c34-94e1-fb45eaa6cb10.png)
![image](https://user-images.githubusercontent.com/12287588/212227443-4a886783-1474-4934-85fe-e385dc408e69.png)

**Comment by gabuch2** [comment]
This function is present in the game's binary file "server.so" as you can see [in the Orpheu signature](https://github.com/gabuch2/OrpheuSignatures/blob/Svengine/configs/orpheu/functions/SC_ShouldBypassEntity).

**Comment by Th3-822** [comment]
Sven Co-op has revised all the playermove code and thats something they added over the PM_PlayerTrace checks, as a callback function to ignore entities
